# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-18.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.4"
    servidorUbuntu.vm.provision "shell", path:"StartUpServidor.sh"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    servidorUbuntu.vm.provider "virtualbox" do |v|
      v.memory = 1536
    end
  end
end